//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace HLBD.pretrade {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DataSet1 : DataSet {
        
        private driverDataTable tabledriver;
        
        public DataSet1() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected DataSet1(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["driver"] != null)) {
                    this.Tables.Add(new driverDataTable(ds.Tables["driver"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public driverDataTable driver {
            get {
                return this.tabledriver;
            }
        }
        
        public override DataSet Clone() {
            DataSet1 cln = ((DataSet1)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["driver"] != null)) {
                this.Tables.Add(new driverDataTable(ds.Tables["driver"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        public void InitVars() {
            this.tabledriver = ((driverDataTable)(this.Tables["driver"]));
            if ((this.tabledriver != null)) {
                this.tabledriver.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "DataSet1";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/DataSet1.xsd";
            this.Locale = new System.Globalization.CultureInfo("zh-CN");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tabledriver = new driverDataTable();
            this.Tables.Add(this.tabledriver);
        }
        
        private bool ShouldSerializedriver() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void driverRowChangeEventHandler(object sender, driverRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class driverDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columndriverid;
            
            private DataColumn columnname_driver;
            
            private DataColumn columnemploytime_driver;
            
            private DataColumn columndrivetimes_driver;
            
            private DataColumn columnaccidenttimes_driver;
            
            private DataColumn columncardtype_driver;
            
            private DataColumn columnidcard_driver;
            
            private DataColumn columnmobilephone_driver;
            
            private DataColumn columnaddress_driver;
            
            private DataColumn columnpostcode_driver;
            
            public driverDataTable() : 
                    base("driver") {
                this.InitClass();
            }
            
            public driverDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            public DataColumn driveridColumn {
                get {
                    return this.columndriverid;
                }
            }
            
            public DataColumn name_driverColumn {
                get {
                    return this.columnname_driver;
                }
            }
            
            public DataColumn employtime_driverColumn {
                get {
                    return this.columnemploytime_driver;
                }
            }
            
            public DataColumn drivetimes_driverColumn {
                get {
                    return this.columndrivetimes_driver;
                }
            }
            
            public DataColumn accidenttimes_driverColumn {
                get {
                    return this.columnaccidenttimes_driver;
                }
            }
            
            public DataColumn cardtype_driverColumn {
                get {
                    return this.columncardtype_driver;
                }
            }
            
            public DataColumn idcard_driverColumn {
                get {
                    return this.columnidcard_driver;
                }
            }
            
            public DataColumn mobilephone_driverColumn {
                get {
                    return this.columnmobilephone_driver;
                }
            }
            
            public DataColumn address_driverColumn {
                get {
                    return this.columnaddress_driver;
                }
            }
            
            public DataColumn postcode_driverColumn {
                get {
                    return this.columnpostcode_driver;
                }
            }
            
            public driverRow this[int index] {
                get {
                    return ((driverRow)(this.Rows[index]));
                }
            }
            
            public event driverRowChangeEventHandler driverRowChanged;
            
            public event driverRowChangeEventHandler driverRowChanging;
            
            public event driverRowChangeEventHandler driverRowDeleted;
            
            public event driverRowChangeEventHandler driverRowDeleting;
            
            public void AdddriverRow(driverRow row) {
                this.Rows.Add(row);
            }
            
            public driverRow AdddriverRow(string driverid, string name_driver, System.DateTime employtime_driver, int drivetimes_driver, int accidenttimes_driver, string cardtype_driver, string idcard_driver, string mobilephone_driver, string address_driver, string postcode_driver) {
                driverRow rowdriverRow = ((driverRow)(this.NewRow()));
                rowdriverRow.ItemArray = new object[] {
                        driverid,
                        name_driver,
                        employtime_driver,
                        drivetimes_driver,
                        accidenttimes_driver,
                        cardtype_driver,
                        idcard_driver,
                        mobilephone_driver,
                        address_driver,
                        postcode_driver};
                this.Rows.Add(rowdriverRow);
                return rowdriverRow;
            }
            
            public driverRow FindBydriverid(string driverid) {
                return ((driverRow)(this.Rows.Find(new object[] {
                            driverid})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                driverDataTable cln = ((driverDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new driverDataTable();
            }
            
            public void InitVars() {
                this.columndriverid = this.Columns["driverid"];
                this.columnname_driver = this.Columns["name_driver"];
                this.columnemploytime_driver = this.Columns["employtime_driver"];
                this.columndrivetimes_driver = this.Columns["drivetimes_driver"];
                this.columnaccidenttimes_driver = this.Columns["accidenttimes_driver"];
                this.columncardtype_driver = this.Columns["cardtype_driver"];
                this.columnidcard_driver = this.Columns["idcard_driver"];
                this.columnmobilephone_driver = this.Columns["mobilephone_driver"];
                this.columnaddress_driver = this.Columns["address_driver"];
                this.columnpostcode_driver = this.Columns["postcode_driver"];
            }
            
            private void InitClass() {
                this.columndriverid = new DataColumn("driverid", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndriverid);
                this.columnname_driver = new DataColumn("name_driver", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnname_driver);
                this.columnemploytime_driver = new DataColumn("employtime_driver", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnemploytime_driver);
                this.columndrivetimes_driver = new DataColumn("drivetimes_driver", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndrivetimes_driver);
                this.columnaccidenttimes_driver = new DataColumn("accidenttimes_driver", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnaccidenttimes_driver);
                this.columncardtype_driver = new DataColumn("cardtype_driver", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columncardtype_driver);
                this.columnidcard_driver = new DataColumn("idcard_driver", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnidcard_driver);
                this.columnmobilephone_driver = new DataColumn("mobilephone_driver", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnmobilephone_driver);
                this.columnaddress_driver = new DataColumn("address_driver", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnaddress_driver);
                this.columnpostcode_driver = new DataColumn("postcode_driver", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnpostcode_driver);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columndriverid}, true));
                this.columndriverid.AllowDBNull = false;
                this.columndriverid.Unique = true;
            }
            
            public driverRow NewdriverRow() {
                return ((driverRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new driverRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(driverRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.driverRowChanged != null)) {
                    this.driverRowChanged(this, new driverRowChangeEvent(((driverRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.driverRowChanging != null)) {
                    this.driverRowChanging(this, new driverRowChangeEvent(((driverRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.driverRowDeleted != null)) {
                    this.driverRowDeleted(this, new driverRowChangeEvent(((driverRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.driverRowDeleting != null)) {
                    this.driverRowDeleting(this, new driverRowChangeEvent(((driverRow)(e.Row)), e.Action));
                }
            }
            
            public void RemovedriverRow(driverRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class driverRow : DataRow {
            
            private driverDataTable tabledriver;
            
            public driverRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tabledriver = ((driverDataTable)(this.Table));
            }
            
            public string driverid {
                get {
                    return ((string)(this[this.tabledriver.driveridColumn]));
                }
                set {
                    this[this.tabledriver.driveridColumn] = value;
                }
            }
            
            public string name_driver {
                get {
                    try {
                        return ((string)(this[this.tabledriver.name_driverColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.tabledriver.name_driverColumn] = value;
                }
            }
            
            public System.DateTime employtime_driver {
                get {
                    try {
                        return ((System.DateTime)(this[this.tabledriver.employtime_driverColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.tabledriver.employtime_driverColumn] = value;
                }
            }
            
            public int drivetimes_driver {
                get {
                    try {
                        return ((int)(this[this.tabledriver.drivetimes_driverColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.tabledriver.drivetimes_driverColumn] = value;
                }
            }
            
            public int accidenttimes_driver {
                get {
                    try {
                        return ((int)(this[this.tabledriver.accidenttimes_driverColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.tabledriver.accidenttimes_driverColumn] = value;
                }
            }
            
            public string cardtype_driver {
                get {
                    try {
                        return ((string)(this[this.tabledriver.cardtype_driverColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.tabledriver.cardtype_driverColumn] = value;
                }
            }
            
            public string idcard_driver {
                get {
                    try {
                        return ((string)(this[this.tabledriver.idcard_driverColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.tabledriver.idcard_driverColumn] = value;
                }
            }
            
            public string mobilephone_driver {
                get {
                    try {
                        return ((string)(this[this.tabledriver.mobilephone_driverColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.tabledriver.mobilephone_driverColumn] = value;
                }
            }
            
            public string address_driver {
                get {
                    try {
                        return ((string)(this[this.tabledriver.address_driverColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.tabledriver.address_driverColumn] = value;
                }
            }
            
            public string postcode_driver {
                get {
                    try {
                        return ((string)(this[this.tabledriver.postcode_driverColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.tabledriver.postcode_driverColumn] = value;
                }
            }
            
            public bool Isname_driverNull() {
                return this.IsNull(this.tabledriver.name_driverColumn);
            }
            
            public void Setname_driverNull() {
                this[this.tabledriver.name_driverColumn] = System.Convert.DBNull;
            }
            
            public bool Isemploytime_driverNull() {
                return this.IsNull(this.tabledriver.employtime_driverColumn);
            }
            
            public void Setemploytime_driverNull() {
                this[this.tabledriver.employtime_driverColumn] = System.Convert.DBNull;
            }
            
            public bool Isdrivetimes_driverNull() {
                return this.IsNull(this.tabledriver.drivetimes_driverColumn);
            }
            
            public void Setdrivetimes_driverNull() {
                this[this.tabledriver.drivetimes_driverColumn] = System.Convert.DBNull;
            }
            
            public bool Isaccidenttimes_driverNull() {
                return this.IsNull(this.tabledriver.accidenttimes_driverColumn);
            }
            
            public void Setaccidenttimes_driverNull() {
                this[this.tabledriver.accidenttimes_driverColumn] = System.Convert.DBNull;
            }
            
            public bool Iscardtype_driverNull() {
                return this.IsNull(this.tabledriver.cardtype_driverColumn);
            }
            
            public void Setcardtype_driverNull() {
                this[this.tabledriver.cardtype_driverColumn] = System.Convert.DBNull;
            }
            
            public bool Isidcard_driverNull() {
                return this.IsNull(this.tabledriver.idcard_driverColumn);
            }
            
            public void Setidcard_driverNull() {
                this[this.tabledriver.idcard_driverColumn] = System.Convert.DBNull;
            }
            
            public bool Ismobilephone_driverNull() {
                return this.IsNull(this.tabledriver.mobilephone_driverColumn);
            }
            
            public void Setmobilephone_driverNull() {
                this[this.tabledriver.mobilephone_driverColumn] = System.Convert.DBNull;
            }
            
            public bool Isaddress_driverNull() {
                return this.IsNull(this.tabledriver.address_driverColumn);
            }
            
            public void Setaddress_driverNull() {
                this[this.tabledriver.address_driverColumn] = System.Convert.DBNull;
            }
            
            public bool Ispostcode_driverNull() {
                return this.IsNull(this.tabledriver.postcode_driverColumn);
            }
            
            public void Setpostcode_driverNull() {
                this[this.tabledriver.postcode_driverColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class driverRowChangeEvent : EventArgs {
            
            private driverRow eventRow;
            
            private DataRowAction eventAction;
            
            public driverRowChangeEvent(driverRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public driverRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
